app/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.posts, name="posts"),
    path('categories/', views.categories, name="categories"),
    path('comments/', views.comments, name="comments"),
    path('users/', views.users, name="users"),
    path('test/', views.test, name="test"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('details/', views.details, name="details"),
]

madmin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render


def index(request):
    context = {
        "title": "Dashboard",
        "message": "From Dashboard Page"
    }
    return render(request, "app/index.html", context)


def posts(request):
    context = {
        "title": "Posts Page",
        "message": "From Posts Page"
    }
    return render(request, "app/posts.html", context)


def categories(request):
    context = {
        "title": "Categories Page",
        "message": "From Categories Page"
    }
    return render(request, "app/categories.html", context)


def comments(request):
    context = {
        "title": "Comments Page",
        "message": "From Comments Page"
    }
    return render(request, "app/comments.html", context)


def users(request):
    context = {
        "title": "Users Page",
        "message": "From Users Page"
    }
    return render(request, "app/users.html", context)


def test(request):
    context = {
        "title": "Testing Page",
        "message": "From testing Page"
    }
    return render(request, "app/test.html", context)


def login(request):
    context = {
        "title": "Login Page",
        "message": "From Login Page"
    }
    return render(request, "app/login.html", context)


def logout(request):
    context = {
        "title": "Logout Page",
        "message": "From Logout Page"
    }
    return render(request, "app/logout.html", context)


def details(request):
    context = {
        "title": "Details Page",
        "message": "From Details Page"
    }
    return render(request, "app/details.html", context)

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block css %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/162ff428c2.js" crossorigin="anonymous"></script>

    <title>{{ title }}</title>
</head>
<body class="grey lighten-3">

<nav class="blue darken-2">
    <div class="container">
        <div class="nav-wrapper">
      <a href="{% url 'app:index' %}" class="brand-logo">JDEVS Dashboard</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'app:index' %}">Dashboard</a></li>
            <li><a href="{% url 'app:posts' %}">Posts</a></li>
            <li><a href="{% url 'app:categories' %}">Categories</a></li>
            <li><a href="{% url 'app:comments' %}">Comments</a></li>
            <li><a href="{% url 'app:users' %}">Users</a></li>
            <li>
                <a
                        href="#"
                        data-target="slide-out"
                        class="sidenav-trigger show-on-large right"
                >
                    <i class="material-icons">menu</i>
                </a>
            </li>
        </ul>

        <ul id="slide-out" class="sidenav">
            <li>
                <div class="user-view">
                    <div class="background">
                        <img src="{% static 'images/ocean.jpg' %}" alt="">
                    </div>
                    <a href="#user"><img class="circle" src="{% static 'images/moi.png' %}" alt=""></a>
                    <a href="#name"><span class="white-text name">Julio Briones</span></a>
                    <a href="#email"><span class="white-text email">contact@jdevs.mx</span></a>
                </div>
            </li>
            <li class="active">
                <a href="{% url 'app:index' %}">
                    <i class="material-icons">dashboard</i>
                    Dashboard
                </a>
            </li>
            <li><a href="{% url 'app:posts' %}">Posts</a></li>
            <li><a href="{% url 'app:categories' %}">Categories</a></li>
            <li><a href="{% url 'app:comments' %}">Comments</a></li>
            <li><a href="{% url 'app:users' %}">Users</a></li>
            <li>
                <div class="divider"></div>
            </li>
            <li><a class="subheader">Account Controls</a></li>
            <li><a class="waves-effect" href="{% url 'app:login' %}">Logout</a></li>
        </ul>


    </div>
    </div>
  </nav>

{% block content %}

{% endblock %}

{% block javascript %}
    <script
        src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous">

    </script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.15.0/standard/ckeditor.js"></script>
    <script src="{% static 'js/chart.js' %}"></script>
    <script type="text/javascript">
        // Hide Sections
        $('.section').hide()

        setTimeout(function () {
            $(document).ready(function () {
                //Show Sections
                $('.section').fadeIn();

                // Hide Preloader
                $('.loader').fadeOut();

                //Custom JS & JQuery here
                $('.sidenav').sidenav();

                // Init Modal
                $('.modal').modal();

                // Init Select
                $('select').formSelect();

                // Generic Counter, used as it is
                $('.count').each(function () {
                    $(this).prop('Counter', 0).animate({
                        Counter: $(this).text()
                    }, {
                        duration: 1000,
                        easing: "swing",
                        step: function (now) {
                            $(this).text(Math.ceil(now));
                        }
                    });
                });

                // Comments Approve & Deny
                $('.approve').click(function (e) {
                    M.toast({
                        html: "Comment approved",
                        displayLength: 3000
                    })
                    e.preventDefault()
                });
                $('.deny').click(function (e) {
                    M.toast({
                        html: "Comment denied",
                        displayLength: 3000
                    })
                    e.preventDefault()
                });

                CKEDITOR.replace( 'body' );

                // Modal
                $('.fixed-action-btn').floatingActionButton();

            });
        }, 1000)

    </script>
{% endblock %}
</body>
</html>

app/templates/app/footer.html
{% load static %}

{% block content %}

    <footer class="section blue darken-2 white-text center">
    <p>JDEVS Panel Copywrite &copy; 2020</p>
    </footer>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
    <!-- Section: Stats -->
    {% include 'app/stats.html' %}

    <!-- Section: Visitors -->
    {% include 'app/visitors.html' %}

    <!-- Section: Recent Posts & Todos -->
    {% include 'app/posts_todos.html' %}

    <!-- Section Footer -->
    {% include 'app/footer.html' %}

    <!-- Fixed Action Button -->
    {% include 'app/action_button.html' %}

    <!-- Section: Preloader -->
    <div class="loader preloader-wrapper big active">
        <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/app/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% block css %}
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/162ff428c2.js" crossorigin="anonymous"></script>

    <title>{{ title }}</title>
</head>
<body class="grey lighten-3">

<!-- Section: Login Nav -->
<nav class="blue darken-2">
    <div class="container">
        <div class="nav-wrapper">
            <a href="{% url 'app:index' %}" class="brand-logo">JDEVS</a>
        </div>
    </div>
</nav>

<!-- Section: Login -->
<section class="section section-login">
    <div class="container">
        <div class="row">
            <div class="col s12 m8 offset-m2 l6 offset-l3">
                <div class="card-panel login blue darken-2 white-text center">
                    <h2>JDEVS Login</h2>
                    <form action="{% url 'app:index' %}">
                        <div class="input-field">
                            <i class="material-icons prefix">email</i>
                            <input type="email" id="email">
                            <label for="email" class="white-text">Email</label>
                        </div>
                        <div class="input-field">
                            <i class="material-icons prefix">lock</i>
                            <input type="password" id="password">
                            <label for="password" class="white-text">Password</label>
                        </div>
                        <input
                                type="submit"
                                value="Login"
                                class="btn btn-large btn-extended grey lighten-4 black-text"
                        >
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Section Footer -->
    {% include 'app/footer.html' %}


{% block javascript %}
    <script
        src="https://code.jquery.com/jquery-3.5.1.js"
        integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
        crossorigin="anonymous">

    </script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script type="text/javascript">
        // Hide Sections
        $('.section').hide()

        setTimeout(function () {
            $(document).ready(function () {
                //Show Sections
                $('.section').fadeIn();

                // Hide Preloader
                $('.loader').fadeOut();

                //Custom JS & JQuery here
                $('.sidenav').sidenav();

                // Init Modal
                $('.modal').modal();

                // Generic Counter, used as it is
                $('.count').each(function () {
                    $(this).prop('Counter', 0).animate({
                        Counter: $(this).text()
                    }, {
                        duration: 1000,
                        easing: "swing",
                        step: function (now) {
                            $(this).text(Math.ceil(now));
                        }
                    });
                });


            });
        }, 1000)

    </script>
{% endblock %}
</body>
</html>

app/templates/app/logout.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}
    <!-- Section: Other -->


    <h1>{{ message }}</h1>
{% endblock %}

app/templates/app/posts.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

    <!-- Section: Posts -->
    <section class="section section-posts grey lighten-4">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">Posts</span>
                        <table class="striped">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Date Created</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Post One</td>
                            <td>Web Development</td>
                            <td>June 12, 2020</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Two</td>
                            <td>Web Development</td>
                            <td>July, 3, 2020</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Three</td>
                            <td>App Upgrading</td>
                            <td>August 25, 2020</td>
                            <td>
                                <a href="" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Four</td>
                            <td>Graphic Design</td>
                            <td>Sept 15, 2020</td>
                            <td>
                                <a href="" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Five</td>
                            <td>App Upgrading</td>
                            <td>Sept 16, 2020</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Six</td>
                            <td>Graphic Design</td>
                            <td>Sept 18, 2020</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    </div>
                    <div class="card-action">
                        <ul class="pagination">
                            <li class="disabled">
                                <a href="#" class="blue-text">
                                    <i class="material-icons">chevron_left</i>
                                </a>
                            </li>
                            <li class="active blue lighten-2">
                                <a href="#" class="white-text">1</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">2</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">3</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">4</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">5</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">
                                    <i class="material-icons">chevron_right</i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>

    <!-- Section: Action Button & Post Modal -->
    <div class="fixed-action-btn">
        <a href="#post-modal" class="modal-trigger btn-floating btn-large red">
            <i class="material-icons">add</i>
        </a>
    </div>

    <!-- Section: Add Post Modal -->
    <div id="post-modal" class="modal">
        <div class="modal-content">
            <h4>Add Post</h4>
            <form action="">
                <div class="input-field">
                    <input type="text" id="title">
                    <label for="title">Title</label>
                </div>
                <div class="input-field">
                    <select name="" id="">
                        <option value="" disabled selected>Select Option</option>
                        <option value="1">App Development</option>
                        <option value="2">Graphic Design</option>
                        <option value="3">Tech Development</option>
                        <option value="4">Other</option>
                    </select>
                    <label for="">Category</label>
                </div>
                <div class="input-field">
                    <textarea name="body" id="body" class="materialize-textarea"></textarea>
                    <label for="body"></label>
                </div>
            </form>
            <div class="modal-footer">
                <a href="" class="modal-action modal-close btn blue white-text">Submit</a>
            </div>
        </div>
    </div>

    <!-- Section Footer -->
    {% include 'app/footer.html' %}
{% endblock %}

app/templates/app/posts_todos.html
{% load static %}

{% block content %}

<section class="section section-recent">
    <div class="row">
        <div class="col s12 m6 l8">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Recent Posts</span>
                    <table class="striped">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Category</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Post One</td>
                            <td>Web Development</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Two</td>
                            <td>Web Development</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Three</td>
                            <td>App Upgrading</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Post Four</td>
                            <td>Graphic Design</td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">Details</a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Quick Todos</span>
                    <form action="" id="todo-form">
                        <div class="input-field">
                            <input id="todo" type="text" placeholder="Add todo...">
                        </div>
                    </form>
                    <ul class="collection todos">
                        <li class="collection-item">
                            <div>Todo One
                                <a href="#" class="secondary-content delete">
                                <i class="material-icons">close</i>
                            </a></div>
                        </li>
                        <li class="collection-item">
                            <div>Todo Two
                                <a href="#" class="secondary-content delete">
                                <i class="material-icons">close</i>
                            </a></div>
                        </li>
                        <li class="collection-item">
                            <div>Todo Three
                                <a href="#" class="secondary-content delete">
                                <i class="material-icons">close</i>
                            </a></div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

app/templates/app/users.html
{% extends 'app/base.html' %}
{% load static %}

{% block content %}

    <!-- Section: Users -->
    <section class="section section-users grey lighten-4">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">Users</span>
                        <table class="striped">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Registered</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td width="70">
                                <img
                                        src="{% static 'images/moi.png' %}"
                                        alt=""
                                        class="responsive circle"
                                        style="width: 40px; margin-left: 10px;"
                                >
                            </td>
                            <td>
                                Julio Briones
                            </td>
                            <td>
                                contact@jdevs.mx
                            </td>
                            <td>
                                Jul, 03 2020
                            </td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">
                                    Details
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td width="70">
                                <img
                                        src="{% static 'images/person1.jpg' %}"
                                        alt=""
                                        class="responsive circle"
                                        style="width: 40px; margin-left: 10px;"
                                >
                            </td>
                            <td>
                                Benito Briones
                            </td>
                            <td>
                                benito@jdevs.mx
                            </td>
                            <td>
                                Aug, 05 2020
                            </td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">
                                    Details
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td width="70">
                                <img
                                        src="{% static 'images/person2.jpg' %}"
                                        alt=""
                                        class="responsive circle"
                                        style="width: 40px; margin-left: 10px;"
                                >
                            </td>
                            <td>
                                Charbel Briones
                            </td>
                            <td>
                                charbel@jdevs.mx
                            </td>
                            <td>
                                Sep, 18 2020
                            </td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">
                                    Details
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td width="70">
                                <img
                                        src="{% static 'images/person3.jpg' %}"
                                        alt=""
                                        class="responsive circle"
                                        style="width: 40px; margin-left: 10px;"
                                >
                            </td>
                            <td>
                                Jane Doe
                            </td>
                            <td>
                                janedoe@jdevs.mx
                            </td>
                            <td>
                                Sep, 23 2020
                            </td>
                            <td>
                                <a href="{% url 'app:details' %}" class="btn blue lighten-2">
                                    Details
                                </a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    </div>
                    <div class="card-action">
                        <ul class="pagination">
                            <li class="disabled">
                                <a href="#" class="blue-text">
                                    <i class="material-icons">chevron_left</i>
                                </a>
                            </li>
                            <li class="active blue lighten-2">
                                <a href="#" class="white-text">1</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">2</a>
                            </li>
                            <li class="waves-effect">
                                <a href="#" class="blue-text">
                                    <i class="material-icons">chevron_right</i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>

    <!-- Section: Action Button -->
    <div class="fixed-action-btn">
        <a href="#user-modal" class="modal-trigger btn-floating btn-large red">
            <i class="material-icons">add</i>
        </a>
    </div>

    <!-- Section: Add User Post Modal -->
    <div id="user-modal" class="modal">
        <div class="modal-content">
            <h4>Add User</h4>
            <form action="">
                <div class="input-field">
                    <input type="text" id="name">
                    <label for="name">Name</label>
                </div>
                <div class="input-field">
                    <input type="email" id="email">
                    <label for="email">Email</label>
                </div>
                <div class="input-field">
                    <input type="password" id="password">
                    <label for="password">Password</label>
                </div>
                <div class="input-field">
                    <input type="password" id="password2">
                    <label for="password2">Confirm Password</label>
                </div>
            </form>
            <div class="modal-footer">
                <a href="" class="modal-action modal-close btn blue white-text">Submit</a>
            </div>
        </div>
    </div>

    <!-- Section Footer -->
    {% include 'app/footer.html' %}

{% endblock %}